#!/usr/bin/env python3
"""Builds the spec feature matrix per format — one source, two products.

    python3 scripts/build-spec-feature-matrix.py            # rebuild the HTML and the YAML under docs/
    python3 scripts/build-spec-feature-matrix.py --check    # do the products match the source? (for CI; exit 1 on a difference)

The only source is scripts/spec-feature-matrix.json. docs/spec-feature-matrix.html and
docs/spec-feature-matrix.yaml are generated, so do not edit them by hand (two places fixed by hand always drift apart).
The look borrows the <style> of docs/format-support.html as it is — it is not copied here, so that the look of
the sibling documents cannot drift apart on its own.

Runs on the standard library alone (no external YAML library).
"""
import json
import os
import re
import sys
import html
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, "scripts", "spec-feature-matrix.json")
STYLE_FROM = os.path.join(ROOT, "docs", "format-support.html")
OUT_HTML = os.path.join(ROOT, "docs", "spec-feature-matrix.html")
OUT_YAML = os.path.join(ROOT, "docs", "spec-feature-matrix.yaml")

ORDER = ["full", "partial", "preserved", "none", "na", "unverified"]
CELL_CLASS = {"full": "y", "partial": "h", "preserved": "", "none": "n", "na": "", "unverified": "h"}
EVIDENCE_LABEL = {"measured": "measured", "code": "code check", "readme": "document",
                  "judge": "judged by the application"}


def e(s):
    return html.escape(str(s), quote=True)


def code(s):
    return "<code>%s</code>" % e(s)


def counts(fmt, side):
    return Counter(r[side] for a in fmt["areas"] for r in a["features"])


def rows_of(fmt):
    return sum(len(a["features"]) for a in fmt["areas"])


# ------------------------------------------------------------------ YAML
def q(s):
    """A double-quoted YAML string. JSON string notation can be used as it is."""
    return json.dumps(s, ensure_ascii=False)


# Put the UTF-8 mark (BOM) at the head of the YAML. The reason lies on the display side: HTML can declare its
# encoding with <meta charset>, but a text file that is not HTML has nowhere to declare it, so the browser looks at
# the server's Content-Type. GitHub Pages serves .yaml as "text/yaml" (with no charset), so the browser guesses
# Latin-1 and non-ASCII text garbles. With a BOM at the head, the browser decides on UTF-8. YAML 1.2 explicitly
# allows a leading BOM (§5.2 Character Encodings), and libyaml-based implementations skip it (confirmed with
# Ruby/Psych).
# **Do not remove it** — without it, readers who open the file from the published page see garbled text.
BOM = "\ufeff"


def emit_yaml(d):
    meta, out = d["meta"], []
    w = out.append
    w("# " + meta["title"])
    w("# Generated. Edit scripts/spec-feature-matrix.json and")
    w("# run scripts/build-spec-feature-matrix.py (do not edit this file by hand).")
    w("meta:")
    for k in ("title", "library_version", "as_of", "commit", "axis", "granularity", "caveat"):
        w("  %s: %s" % (k, q(meta[k])))
    w("  environments:")
    for x in meta["environments"]:
        w("    - %s" % q(x))
    w("  status_vocabulary:")
    for key, v in meta["status_vocabulary"].items():
        w("    %s:" % key)
        w("      symbol: %s" % q(v["symbol"]))
        w("      meaning: %s" % q(v["meaning"]))
    w("  evidence_types:")
    for key, v in meta["evidence_types"].items():
        w("    %s: %s" % (key, q(v)))
    w("  common_api:")
    for key, v in meta["common_api"].items():
        w("    %s: %s" % (key, q(v)))
    w("")
    w("formats:")
    for f in d["formats"]:
        w("  - id: %s" % q(f["id"]))
        w("    name: %s" % q(f["name"]))
        w("    spec:")
        w("      name: %s" % q(f["spec"]["name"]))
        w("      public: %s" % ("true" if f["spec"]["public"] else "false"))
        w("      note: %s" % q(f["spec"]["note"]))
        w("    totals:")
        for side in ("read", "write"):
            c = counts(f, side)
            w("      %s: {%s}" % (side, ", ".join("%s: %d" % (k, c[k]) for k in ORDER)))
        w("      rows: %d" % rows_of(f))
        w("    areas:")
        for a in f["areas"]:
            w("      - id: %s" % q(a["id"]))
            w("        name: %s" % q(a["name"]))
            w("        features:")
            for r in a["features"]:
                w("          - id: %s" % q(r["id"]))
                w("            name: %s" % q(r["name"]))
                w("            spec_anchor: %s" % q(r["spec_anchor"]))
                w("            read: %s" % q(r["read"]))
                w("            write: %s" % q(r["write"]))
                if r["api"]:
                    w("            api:")
                    for x in r["api"]:
                        w("              - %s" % q(x))
                else:
                    w("            api: []")
                w("            warning: %s" % (q(r["warning"]) if r["warning"] else "null"))
                w("            evidence: %s" % q(r["evidence"]))
                w("            note: %s" % (q(r["note"]) if r["note"] else "null"))
    return BOM + "\n".join(out) + "\n"


# ------------------------------------------------------------------ HTML
FIGURE = """<figure>
<svg viewBox="0 0 900 300" role="img" aria-label="The four outcomes a feature can meet, side by side">
  <rect x="0" y="10" width="210" height="132" rx="14" class="sv-card"/>
  <text x="20" y="42" class="sv-good" font-size="24">○</text>
  <text x="52" y="42" class="sv-tb">Round-trips as is</text>
  <text x="20" y="70" class="sv-t2">Read in the model's terms,</text>
  <text x="20" y="90" class="sv-t2">and the same is written out.</text>
  <text x="20" y="110" class="sv-t2">The API has the feature.</text>
  <text x="20" y="130" class="sv-t3">e.g. merged cells</text>

  <rect x="230" y="10" width="210" height="132" rx="14" class="sv-card"/>
  <text x="250" y="42" class="sv-warn" font-size="24">△</text>
  <text x="282" y="42" class="sv-tb">In another shape</text>
  <text x="250" y="70" class="sv-t2">The other format has no</text>
  <text x="250" y="90" class="sv-t2">words for it, so something</text>
  <text x="250" y="110" class="sv-t2">close stands in, always said.</text>
  <text x="250" y="130" class="sv-t3">e.g. number format sections</text>

  <rect x="460" y="10" width="210" height="132" rx="14" class="sv-card"/>
  <text x="480" y="42" class="sv-t" font-size="24">▣</text>
  <text x="512" y="42" class="sv-tb">Preserved</text>
  <text x="480" y="70" class="sv-t2">Not read into the model;</text>
  <text x="480" y="90" class="sv-t2">saving to the same format</text>
  <text x="480" y="110" class="sv-t2">keeps its bytes as-is (F3).</text>
  <text x="480" y="130" class="sv-t3">e.g. charts, VBA, sparklines</text>

  <rect x="690" y="10" width="210" height="132" rx="14" class="sv-card"/>
  <text x="710" y="42" class="sv-bad" font-size="24">×</text>
  <text x="742" y="42" class="sv-tb">Dropped, reported</text>
  <text x="710" y="70" class="sv-t2">Does not go through, but it</text>
  <text x="710" y="90" class="sv-t2">never vanishes in silence:</text>
  <text x="710" y="110" class="sv-t2">a warning always follows.</text>
  <text x="710" y="130" class="sv-t3">e.g. the Numbers print setup</text>

  <rect x="0" y="170" width="900" height="106" rx="14" class="sv-soft"/>
  <text x="24" y="200" class="sv-tb">How ▣ differs from ○</text>
  <text x="24" y="226" class="sv-t2">It survives in full as long as it is saved back to the same format, but the model has no words for it:</text>
  <text x="24" y="248" class="sv-t2">the API cannot touch it, and it cannot be carried to another format. The moment it is converted, it is treated like ×,</text>
  <text x="24" y="268" class="sv-t2">and only then is a warning raised. So "supported or not" cannot say it, and this table uses six symbols.</text>
</svg>
<figcaption>The symbols of this table. Telling × apart from ▣ is at the heart of this table.</figcaption>
</figure>"""


def status_cell(meta, value):
    sym = meta["status_vocabulary"][value]["symbol"]
    cls = CELL_CLASS[value]
    return '<td class="m%s">%s</td>' % ((" " + cls) if cls else "", e(sym))


def format_table(meta, f):
    out = ['<div class="tablewrap"><table>']
    out.append("<thead><tr><th>Feature</th><th class=\"m\">Read</th><th class=\"m\">Write</th>"
               "<th>Where in the spec</th><th>API</th><th>Note (what is reported when it is dropped; evidence)</th></tr></thead><tbody>")
    for a in f["areas"]:
        out.append('<tr class="group"><td colspan="6">%s</td></tr>' % e(a["name"]))
        for r in a["features"]:
            note = []
            if r["warning"]:
                note.append("<strong>Warning</strong>: " + e(r["warning"]))
            if r["note"]:
                note.append(e(r["note"]))
            note.append('<span class="chip">%s</span>' % e(EVIDENCE_LABEL[r["evidence"]]))
            anchor = code(r["spec_anchor"]) if r["spec_anchor"] not in ("—", "") else "—"
            api = " ".join(code(x) for x in r["api"]) if r["api"] else "—"
            out.append("<tr><td>%s</td>%s%s<td>%s</td><td>%s</td><td>%s</td></tr>"
                       % (e(r["name"]), status_cell(meta, r["read"]), status_cell(meta, r["write"]),
                          anchor, api, " ".join(note)))
    out.append("</tbody></table></div>")
    return "\n".join(out)


def counts_table(d):
    out = ['<div class="tablewrap"><table>',
           "<thead><tr><th>Format</th><th>Direction</th>"
           + "".join('<th class="m">%s</th>' % e(d["meta"]["status_vocabulary"][k]["symbol"]) for k in ORDER)
           + '<th class="m">Rows</th></tr></thead><tbody>']
    for f in d["formats"]:
        total = rows_of(f)
        for side, label in (("read", "Read"), ("write", "Write")):
            c = counts(f, side)
            out.append("<tr><td>%s</td><td>%s</td>%s<td class=\"m\">%d</td></tr>"
                       % (e(f["name"]), label,
                          "".join('<td class="m">%d</td>' % c[k] for k in ORDER), total))
    out.append("</tbody></table></div>")
    return "\n".join(out)


def load_style():
    with open(STYLE_FROM, encoding="utf-8") as fh:
        m = re.search(r"<style>(.*?)</style>", fh.read(), re.S)
    if not m:
        sys.exit("❌ cannot extract the <style> from %s" % STYLE_FROM)
    return m.group(1)


def short_format_name(name):
    """The format name without its parenthesised extensions: "Excel (.xlsx / .xlsm)" -> "Excel"."""
    return re.split(r"\s*[(\uff08]", name, maxsplit=1)[0]


def emit_html(d):
    meta = d["meta"]
    total = sum(rows_of(f) for f in d["formats"])
    unverified = [(f["name"], r["name"]) for f in d["formats"] for a in f["areas"]
                  for r in a["features"] if "unverified" in (r["read"], r["write"])]
    o = []
    w = o.append
    w('<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="utf-8">')
    w('<meta name="viewport" content="width=device-width, initial-scale=1">')
    w("<title>The spec feature matrix — how far SwiftSheets handles the features in each format's specification"
      " (SwiftSheets %s)</title>" % e(meta["library_version"]))
    w("<style>%s</style>\n</head>\n<body>\n<main>" % load_style())
    w("<h1>The spec feature matrix</h1>")
    w('<p class="lede">The features that the <strong>public specifications</strong> of Excel, OpenDocument and Numbers '
      "each have, set out in %d rows: whether SwiftSheets reads each one, whether it writes it, and which API reaches it. "
      "Where the sibling <a href=\"format-support.html\">format support table</a> measures \"the model's 48 features → 3 formats\", "
      "this table looks the <strong>other way round</strong>: \"a format's specification → SwiftSheets\".</p>" % total)
    w('<p class="meta">As of %s / SwiftSheets %s / verified with: %s</p>'
      % (e(meta["as_of"]), e(meta["library_version"]), e(", ".join(meta["environments"]))))
    w('<hr class="rule">')

    w("<section>\n<h2>Which way this table reads</h2>")
    w("<p>%s</p>" % e(meta["axis"].replace("docs/format-support.html", "the format support table")))
    w("<p>%s</p>" % e(meta["granularity"]))
    w('<div class="grid">')
    for f in d["formats"]:
        cr, cw = counts(f, "read"), counts(f, "write")
        w('<div class="card score"><div class="num">%d<small> features</small></div>'
          '<div class="lab">%s</div><div class="sub">Read ○%d △%d ▣%d ×%d / Write ○%d △%d ▣%d ×%d<br>%s</div></div>'
          % (rows_of(f), e(f["name"]),
             cr["full"], cr["partial"], cr["preserved"], cr["none"],
             cw["full"], cw["partial"], cw["preserved"], cw["none"],
             "Public specification" if f["spec"]["public"]
             else "<strong>No public specification</strong> — built from the Help and observation"))
    w("</div>\n</section>")

    w("<section>\n<h2>Six symbols — why this is not a choice between \"supported\" and \"unsupported\"</h2>")
    w("<p>Two things can both be \"unsupported\" and still mean quite different things to the user: "
      "① something the model merely has no words for, which survives when the file is saved (▣), and "
      "② something that really disappears (×). "
      "Read and write are kept apart too — because there really are rows such as Numbers array formulas, which are read "
      "but not written, and filters, of which only the hidden rows are read.</p>")
    w(FIGURE)
    w('<div class="tablewrap"><table><thead><tr><th class="m">Symbol</th><th>Meaning</th></tr></thead><tbody>')
    for key, v in meta["status_vocabulary"].items():
        cls = CELL_CLASS[key]
        w('<tr><td class="m%s">%s</td><td>%s</td></tr>'
          % ((" " + cls) if cls else "", e(v["symbol"]), e(v["meaning"])))
    w("</tbody></table></div>")
    w("<p>%s</p>" % e(meta["caveat"]))
    w("</section>")

    w("<section>\n<h2>The evidence for each row</h2>")
    w("<p>A table that says \"supported\" is soon a lie. So each row ends with a mark saying "
      "<strong>where its verdict came from</strong>.</p>")
    w('<div class="tablewrap"><table><thead><tr><th>Mark</th><th>Meaning</th></tr></thead><tbody>')
    for key, v in meta["evidence_types"].items():
        w("<tr><td>%s</td><td>%s</td></tr>" % (e(EVIDENCE_LABEL[key]), e(v)))
    w("</tbody></table></div>")
    if unverified:
        w("<p><strong>The honest remainder</strong>: %d row(s) have not been measured"
          " (%s). There is no specimen at hand, so rather than write ○ or × by guesswork they are left as"
          " <code>?</code>.</p>"
          % (len(unverified), e("; ".join("%s: %s" % (short_format_name(n), r) for n, r in unverified))))
    w("</section>")

    w("<section>\n<h2>The entry points every row shares</h2>")
    w('<pre><code>%s</code></pre>'
      % e("Read:    " + meta["common_api"]["read"] + "\n"
          + "Write:   " + meta["common_api"]["write"] + "\n"
          + "Detect:  " + meta["common_api"]["detect"] + "\n"
          + "Receiving what was dropped: " + meta["common_api"]["warnings"]))
    w("</section>")

    w("<section>\n<h2>Counts</h2>")
    w(counts_table(d))
    w('<p class="meta">"—" marks a row that is not applicable: the format has no such concept. Numbers has many "—" '
      "not because it can do less, but because the rows that list Excel and OpenDocument features have no counterpart "
      "on the Numbers side.</p>")
    w("</section>")

    for f in d["formats"]:
        w("<section>\n<h2>%s</h2>" % e(f["name"]))
        w("<p><strong>Specification</strong>: %s</p>" % e(f["spec"]["name"]))
        w("<p>%s</p>" % e(f["spec"]["note"]))
        w(format_table(meta, f))
        w("</section>")

    w("<section>\n<h2>Checking this table yourself</h2>")
    w("<p>Rows marked \"%s\" are backed directly by the tests in the repository.</p>" % e(EVIDENCE_LABEL["measured"]))
    w("<pre><code>swift test --filter FormatSupport   # writes the 48 features to every format and reads them back; pins what survives and the warning counts\n"
      "swift test --filter CrossFormat     # the per-direction (A → B) checks\n"
      "swift test                          # everything\n\n"
      "python3 scripts/build-spec-feature-matrix.py --check   # does this table match its source?</code></pre>")
    w("<p>To change the table, edit <code>scripts/spec-feature-matrix.json</code> and "
      "run <code>python3 scripts/build-spec-feature-matrix.py</code>. "
      "This HTML and <a href=\"spec-feature-matrix.yaml\">the YAML with the same content</a> are generated.</p>")
    w("<p class=\"meta\">The YAML begins with a UTF-8 mark (BOM). Unlike HTML, it has nowhere to declare its "
      "encoding, and GitHub Pages serves <code>text/yaml</code> with no charset, so without the mark "
      "a browser garbles non-ASCII text. YAML 1.2 allows a leading mark, so "
      "code that loads the file needs no change.</p>")
    w("</section>")

    w("<footer>")
    w("SwiftSheets — the spec feature matrix. Measurements and code checks as of SwiftSheets %s (commit %s).<br>"
      % (e(meta["library_version"]), e(meta["commit"])))
    w("The table measured from the model's side is <a href=\"format-support.html\">the format support table</a>; "
      "the behaviour per direction (A → B) is in <a href=\"interoperability.html\">the interoperability guide</a>.<br>")
    w("The implementation decisions and their reasons are in <code>docs/implementation-spec.html</code>, Appendix B.")
    w("</footer>")
    w("</main>\n</body>\n</html>")
    return "\n".join(o) + "\n"


# README.md and docs/index.html state this table's row count in their text. A number is checked, not
# remembered, so --check looks there too (it keeps the README's figure from going stale on its own).
CLAIMS = [("README.md", r"\((\d+) rows;"), ("docs/index.html", r"(\d+) rows\.")]


def check_claims(total):
    stale = []
    for name, pattern in CLAIMS:
        path = os.path.join(ROOT, name)
        try:
            with open(path, encoding="utf-8") as fh:
                text = fh.read()
        except FileNotFoundError:
            stale.append("%s not found" % name)
            continue
        found = re.search(pattern, text)
        if not found:
            stale.append("%s does not state the row count (nothing matches %s)" % (name, pattern))
        elif int(found.group(1)) != total:
            stale.append("%s says %s rows, but there are now %d" % (name, found.group(1), total))
    return stale


def main():
    check = "--check" in sys.argv[1:]
    with open(SOURCE, encoding="utf-8") as fh:
        d = json.load(fh)
    products = [(OUT_YAML, emit_yaml(d)), (OUT_HTML, emit_html(d))]
    if check:
        stale = []
        for path, text in products:
            try:
                with open(path, encoding="utf-8") as fh:
                    current = fh.read()
            except FileNotFoundError:
                current = None
            if current != text:
                stale.append(os.path.relpath(path, ROOT))
        if stale:
            print("❌ the generated files do not match the source: %s\n   run python3 scripts/build-spec-feature-matrix.py."
                  % ", ".join(stale), file=sys.stderr)
            return 1
        total = sum(rows_of(f) for f in d["formats"])
        wrong = check_claims(total)
        if wrong:
            print("❌ text that states the row count is stale:\n   - %s" % "\n   - ".join(wrong), file=sys.stderr)
            return 1
        print("✅ the generated files and the text that states the row count match the source (%d rows)" % total)
        return 0
    for path, text in products:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text)
        print("✅ %s (%d B)" % (os.path.relpath(path, ROOT), len(text.encode("utf-8"))))
    return 0


if __name__ == "__main__":
    sys.exit(main())
